# Generated by Django 5.1.5 on 2025-11-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Full name of the country', max_length=100, null=True)),
                ('phoneCode', models.CharField(blank=True, help_text='International dialing code', max_length=200, null=True)),
                ('emojiU', models.CharField(blank=True, help_text='Unicode emoji flag representation', max_length=500, null=True)),
                ('native', models.CharField(blank=True, help_text='Native name of the country', max_length=100, null=True)),
                ('shortCode', models.CharField(blank=True, help_text='shortCode name of the country', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this country is active or not')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_continent_country')],
            },
        ),
    ]
