# Generated by Django 5.1.5 on 2025-11-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='country',
            name='unique_continent_country',
        ),
        migrations.RemoveField(
            model_name='country',
            name='shortCode',
        ),
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
